import {
  FaHome,
  FaShoppingCart,
  FaUserFriends,
  FaMoneyCheckAlt,
  FaBell,
  FaThLarge,
  FaBoxOpen,
  FaTruck,
  FaUsersCog,
  FaMapMarkerAlt,
  FaExchangeAlt,
  FaChartLine,
  FaHandshake,
  FaInbox,
  FaTags,
  FaPaintBrush,
  FaFileInvoiceDollar,
  FaCogs,
  FaPuzzlePiece,
  FaRocket,
  FaFileContract,
  FaInfoCircle,
  FaPhoneAlt,
  FaLifeRing,
  FaCaretSquareDown,
  FaSitemap,
  FaCamera,
  FaReceipt,
  FaBookOpen,
  FaBox,
  FaClipboardList,
  FaUsers,
  FaMoneyBillWave,
  FaEllipsisH
} from "react-icons/fa";
import { FaSailboat } from "react-icons/fa6";
import { FiMessageSquare } from "react-icons/fi";

export const ADMIN_SIDEBAR_LINKS = [
  {
    key: "dashboard",
    label: "Dashboard",
    href: "/admin",
    icon: <FaHome />,
  },
  {
    key: "pos",
    label: "POS",
    href: "/admin/pos",
    icon: <FaReceipt />,
  },
  {
    key: "orders",
    label: "Orders",
    href: "/admin/orders",
    icon: <FaShoppingCart />,
  },
  {
    key: "quotations",
    label: "Order Requests",
    href: "/admin/quotations",
    icon: <FaFileInvoiceDollar />,
  },
  {
    key: "partial-return-requests",
    label: "Partial Returns",
    href: "/admin/partial-return-requests",
    icon: <FaExchangeAlt />,
  },
  {
    key: "cancel-requests",
    label: "Cancel Requests",
    href: "/admin/cancel-requests",
    icon: <FaCaretSquareDown />,
  },
  {
    key: "payment-links",
    label: "Payment Links",
    href: "/admin/payment-links",
    icon: <FaMoneyCheckAlt />,
  },
  {
    key: "queries",
    label: "Queries",
    href: "/admin/queries",
    icon: <FiMessageSquare />,
  },
  {
    key: "categories",
    label: "Categories",
    href: "/admin/categories",
    icon: <FaThLarge />,
  },
  {
    key: "subCategories",
    label: "Sub Categories",
    href: "/admin/subCategories",
    icon: <FaSitemap />,
  },
  {
    key: "products",
    label: "Products",
    href: "/admin/products",
    icon: <FaBoxOpen />,
  },
  {
    key: "brands",
    label: "Brands",
    href: "/admin/brands",
    icon: <FaSailboat />,
  },
  {
    key: "design-studio",
    label: "Groups",
    href: "/admin/design-studio",
    icon: <FaCamera />,
  },
  {
    key: "websiteLayout",
    label: "Website Layout",
    href: "/admin/website-layout",
    icon: <FaHome />,
  },
  {
    key: "appLayout",
    label: "App Layout",
    href: "/admin/app-layout",
    icon: <FaHome />,
  },
  {
    key: "couponCodes",
    label: "Coupon Codes",
    href: "/admin/couponCodes",
    icon: <FaTags />,
  },
  {
    key: "customers",
    label: "Customers",
    href: "/admin/customers",
    icon: <FaUserFriends />,
  },
  {
    key: "employees",
    label: "Employees",
    href: "/admin/employees",
    icon: <FaUsersCog />,
  },
  {
    key: "notifications",
    label: "Notifications",
    href: "/admin/notifications",
    icon: <FaBell />,
  },
  {
    key: "reports-products",
    label: "Product Reports",
    href: "/admin/reports/products",
    icon: <FaBox />,
  },
  {
    key: "reports-orders-quotations",
    label: "Orders & Quotations",
    href: "/admin/reports/orders-quotations",
    icon: <FaClipboardList />,
  },
  {
    key: "reports-customers",
    label: "Customer Reports",
    href: "/admin/reports/customers",
    icon: <FaUsers />,
  },
  {
    key: "reports-profit-loss-stock",
    label: "Profit & Loss / Stock",
    href: "/admin/reports/profit-loss-stock",
    icon: <FaMoneyBillWave />,
  },
  {
    key: "reports-others",
    label: "Other Reports",
    href: "/admin/reports/others",
    icon: <FaEllipsisH />,
  },
  {
    key: "policies",
    label: "Policies",
    href: "/admin/policies",
    icon: <FaFileContract />,
  },
  {
    key: "blogs",
    label: "Blogs",
    href: "/admin/blogs",
    icon: <FaBookOpen />,
  },
  {
    key: 'settings',
    label: 'Settings',
    href: '/admin/settings',
    icon: <FaCogs />,
  },
];
